# Generated by Django 4.0.4 on 2022-08-05 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_interested_course_stages_order_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
    ]
