# Generated by Django 3.2.12 on 2022-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_interested_course_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='levels',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
